version: '3.5'

services:
  pagamento:
    container_name: 'pagamento'
    image: node:16
    restart: always
    working_dir: /app
    ports:
      - 3333:3333
    volumes:
      - ./dist/:/app/dist/
      - ./package.json:/app/package.json
    command: bash -c "npm install --omit=dev -f && npm run start"

networks:
  default:
    name: local
